---
# update to most recent version
- name: update ansible
  hosts: localhost
  roles:
    - { role: qmailtoaster }
  tasks:
    - git:
        repo: "https://github.com/hightekvagabond/QBSWebServer.git"
        dest: /home/ubuntu/QBSWebServer
        update: yes
        version: master

    - name: add git role
      command: cd /home/ubuntu/QBSWebServer && ansible-galaxy install -r requirements.yml -p roles/

    - cron:
        name: "Cronjob Entry to update nightly"
        minute: "33"
        hour: "4"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/bin/ansible-playbook --connection=local /home/ubuntu/QBSWebServer/ansible/update_from_git.yml"
        #become_user: "{{ admin_user }}"
      become_user: "ubuntu"
...
